// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bctqeqfeteqlaldzrtgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdHFlcWZldGVxbGFsZHpydGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTMxNjYsImV4cCI6MjA1OTc4OTE2Nn0.x6DjsNTIjd2xVWbAHmWtYgdDCBtipPahOKnxzxW__r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);